### ISSUE TITLE
Migrate SBT plugin sbt-sri-platform to SBT1.x / Scala2.12

### ISSUE THREAD

**Issue by frgomes** [scalajs-react-interface/discuss#11]
Migrating sbt-sri-platform requires migration of several other projects.
For those it may interest:
* http://github.com/frgomes/sri
* http://github.com/frgomes/sbt-sri-platform
* http://github.com/frgomes/sri-mobile.g8
* http://github.com/frgomes/sri-core
* http://github.com/frgomes/sri-mobile
* http://github.com/frgomes/sri-universal
* http://github.com/frgomes/sri-vector-icons
* http://github.com/frgomes/sri-navigation
* http://github.com/frgomes/sri-platform-config-android
* http://github.com/frgomes/sri-platform-config-ios

**Comment by frgomes** [comment]
We stumbled at: https://github.com/sbt/librarymanagement/issues/134

This difficulty basically means that ``ios`` and ``android`` are no longer acceptable in dependencies like shown below:
```scala
libraryDependencies ++= Seq(
  "scalajs-react-interface" %%% "core"                    % versions.sri,
  "scalajs-react-interface" %%% "mobile"                  % versions.sri,
  "scalajs-react-interface" %%% "universal"               % versions.sri,
  "scalajs-react-interface" %%% "vector-icons"            % versions.sri,
  "scalajs-react-interface" %%% "platform-config-ios"     % versions.sri % ios,
  "scalajs-react-interface" %%% "platform-config-android" % versions.sri % android,
  "scalajs-react-interface" %%% "navigation"              % versions.sri
)
```

Should I write ``Ios`` instead? Or maybe ``IOS``? Is ``ios`` of such importance that it should be written capitalized or all uppercase? What about [triplets](https://wiki.osdev.org/Target_Triplet)? Should I capitalize a triplet? 

I find this new requirement introduced by SBT 1.x hard to swallow.

**Comment by frgomes** [comment]
Even with the current (and new!) requirement of capitalized configurations in SBT, you can still use strings instead of names of configurations, like this:
```scala
  "scalajs-react-interface" %%% "platform-config-ios"     % versions.sri % "ios",
  "scalajs-react-interface" %%% "platform-config-android" % versions.sri % "android",
```
However, I don't see need of creating artificial configuration names.
If ``ios`` makes plenty of sense, why should I invent some artificial ``PlatformIOS`` just to satisfy SBT?

**Comment by frgomes** [comment]
Tracking PR: https://github.com/sbt/librarymanagement/pull/242

**Comment by virtualirfan** [comment]
I see sbt/librarymanagement#242 got closed.

If `sbt` is bent on insisting capitalization, I don't know if that fight is worth fighting. Most people just copy/paste SBT configurations any way. Thoughts? Thanks for taking this up!

**Comment by frgomes** [comment]
The PR was rejected. :-1: 

This is dued to a new syntax introduced by SBT1.x which is ambiguous.
In order to disambiguate, configurations must be capitalized. Or should I say Configurations?

**Comment by frgomes** [comment]
Duplicate of https://github.com/scalajs-react-interface/sri/issues/15
