### ISSUE TITLE
Consolidate examples via SBT g8Scaffold

### ISSUE THREAD

**Issue by frgomes** [scalajs-react-interface/discuss#6]
Giter8 provides a scaffold functionality which we could be taking advantage of.
Documentation: http://www.foundweekends.org/giter8/scaffolding.html

## Proposal

1. When you first generate a project using mobile.g8, it creates a simple app, which contains only a blank screen (almost!) with some text saying that you can scaffold among a number of options:

  * stack_navigation
  * tab_navigation
  * drawer_navigation

... or even some small apps or examples, such as:

  * capabilities (test device capabilities)
  * other small/sample applications contributed by the community.

2. The developer can then decide for a certain navigation style, such as:

    sbt g8Scaffold myproject com.example drawer_navigation

3. In this case, an additional folder is created, containing the files necessary for implementation of such navigation style.

4. Some wiring is necessary in order to tell that the new navigation style must be used, and not the previous one being used.

### Advantages

1. We can provide various navigation styles and even examples of simple applications;

2. The developer can choose whatever styles/examples better suit his/her purposes;

3. There's no mix or confusion regarding files involved in each style/example, since these files are necessarily separated on distinct folder for each purpose;

4. In case of overwriting some files, this is kept to a minimum, possibly only a configuration file containing just one line which says which is the desired style/example.

5. All items above imply on easier management of changes.

**Comment by virtualirfan** [comment]
@frgomes Now that your PR is merged, can we close this PR.
