### ISSUE TITLE
Include sbt-node into project mobile.g8

### ISSUE THREAD

**Issue by frgomes** [scalajs-react-interface/discuss#9]
http://github.com/jokade/sbt-node

**Comment by virtualirfan** [comment]
Thanks @frgomes.

I'm not familiar with sbt-node. Could you provide some tradeoffs, and design implications, pros/cons. At the high level, a justification for why we should do this would be appreciated.

**Comment by frgomes** [comment]
@virtualirfan :: Let's close this down. I vote for implementing whatever we find useful in our own SBT plugin.
